runtime: nodejs16

instance_class: F2

env_variables:
  API_KEY: "AIzaSyCerq7huPOqxVT95gbSHEzNxyQLVs521x0"

handlers:
  - url: /*
    secure: always
    redirect_http_response_code: 301
    script: auto
